version: '2'
volumes:
  data-postgres:
    driver: "local"
  data-opennms:
    driver: "local"
networks:
  onms-net:
    driver: bridge
services:
  database:
    image: postgres:9.6
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - onms-net
  opennms:
    image: opennms
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Berlin
      - OPENNMS_DBNAME=opennms
      - OPENNMS_DBUSER=opennms
      - OPENNMS_DBPASS=opennms
      - OPENNMS_HOME=/opt/opennms
      - OPENNMS_DB_CONFIG=/opt/opennms/etc/opennms-datasources.xml
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
    networks:
      - onms-net
    command: ["-s"]
    ports:
      - "8980"
    volumes:
      - data-opennms:/opt/opennms/etc
      - data-opennms:/opt/opennms/share/rrd
      - data-opennms:/opt/opennms/share/reports