 version: 2
 jobs:
   build:
     working_directory: ~/docker-build-dev
     machine: true
     steps:
       - checkout
       - run: docker version
       - run: sudo service docker stop
       - run: curl -fsSL https://get.docker.com/ | sudo sh
       - run: docker version
       - run:
          name: Build OpenNMS Horizon Docker image
          command: |
            env
            docker build -t horizon-core-web-${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM} .