 version: 2
 jobs:
   build:
     working_directory: ~/docker-build-dev
     machine: true
     steps:
       - checkout
       - run: docker version
       - run: sudo service docker stop
       - run: curl -fsSL https://get.docker.com/ | sudo sh
       - run: docker version
       - setup_remote_docker
       - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              docker-compose
       - run:
          name: Build OpenNMS Horizon Docker image
          command: |
            env
            docker build -t horizon-core-web .