version: 2
 jobs:
   build:
     working_directory: ~/docker-build-env
     docker:
       - image: ubuntu:14.04
     steps:
       - checkout
       - setup_remote_docker
       - run: echo "hello world"